# Generated by Django 5.2.1 on 2025-06-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('admin', 'admin')], default='user', max_length=15),
        ),
    ]
